# Generated by Django 3.1.2 on 2020-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('tasks', '0003_auto_20201013_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='candidates',
            field=models.ManyToManyField(related_name='aspirant', to='candidates.Candidate'),
        ),
    ]
