# Generated by Django 3.1.2 on 2020-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='candidates',
        ),
    ]
